name: audioplayers
description: A Flutter plugin to play multiple audio files simultaneously
version: 0.17.4
homepage: https://github.com/luanpotter/audioplayers

flutter:
  plugin:
    platforms:
      android:
        package: xyz.luan.audioplayers
        pluginClass: AudioplayersPlugin
      ios:
        pluginClass: AudioplayersPlugin
      macos:
        pluginClass: AudioplayersPlugin

dependencies:

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^0.12.2
  test: ^1.15.4

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

